name: test_cases

on:
  push:
    branches:
      - dev-v2

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: Check Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
            cd ./backend
            npm install
      - name: Start backend server
        run: |
            pwd

    #   - name: Start backend server
    #     working-directory: Appli-Tracker/backend
    #     run: |
    #       nohup node server.js > server.log 2>&1 &

    #   - name: Run Jest tests
    #     working-directory: Appli-Tracker/backend
    #     run: npx jest

    #   - name: Stop backend server
    #     run: |
    #       pkill -f "node server.js"