name: test_cases

on:
  push:
    branches:
      - dev-v2

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: Check Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and run backend server
        run: |
            cd ./backend
            npm install
      - name: Running Unit Test Cases
        run: |
            cd ./backend
            npx jest
      - name: Show Code Coverage
        run: |
            cd ./backend
            npx jest --coverage --verbose
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: 063125bd-5fac-4196-806b-d6224909af5e
          slug: SWEN-732-Team-5/Appli-Tracker







    #   - name: Start backend server
    #     working-directory: Appli-Tracker/backend
    #     run: |
    #       nohup node server.js > server.log 2>&1 &

    #   - name: Run Jest tests
    #     working-directory: Appli-Tracker/backend
    #     run: npx jest

    #   - name: Stop backend server
    #     run: |
    #       pkill -f "node server.js"